### ISSUE TITLE
Замечания по HttpUrl 6.1.7

### ISSUE THREAD

**Issue by lulldev** [lulldev/oop#4]
- [ ] Избавиться от дублирования данных в классе кастомного исключения. Подумать стоит ли создавать на каждую ошибку парсинга отдельный класс. Обновить тесты

- [ ]  Поправить названия переменных согласно стилю кодирования

- [ ]  Доработать основной метод разбора строки с урлом. Постараться избавиться от switch-case в цикле

k = 0.7

**Comment by alexey-malov** [comment]
- [ ] Программа должна быть нечувствительной к регистру символа протокола

**Comment by alexey-malov** [comment]
> Избавиться от дублирования данных в классе кастомного исключения. Подумать стоит ли создавать на каждую ошибку парсинга отдельный класс. Обновить тесты

исправлно

**Comment by alexey-malov** [comment]
> Поправить названия переменных согласно стилю кодирования

Исправлено

**Comment by alexey-malov** [comment]
- [ ] Порт за пределами диапазона [1-65535] должен считаться некорректным. Сейчас порт 65536 превращается в 0
